version: "3.8"
services:
  db:
    image: "postgres"
    container_name: "anime-postgres"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: anime
    ports:
      - "5433:5432"
    volumes:
      - ./pg-data:/var/lib/postgresql/data
  
  pg-admin:
    image: "dpage/pgadmin4"
    container_name: "pg_admin"
    environment:
    - PGADMIN_DEFAULT_EMAIL=azourelli@gmail.com
    - PGADMIN_DEFAULT_PASSWORD=admin
    - PGADMIN_LISTEN_PORT=80
    ports:
    - "8081:80"
    links:
    - "db"