version: "3.8"
services:
  db:
    image: "postgres"
    container_name: "anime-postgres"
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik-secure.tls.certresolver=namecheap"
      - "traefik.http.routers.traefik-secure.rule=Host(`ani.cafe`)"

  supertokens:
    image: "registry.supertokens.io/supertokens/supertokens-postgresql"
    container_name: "supertokens"
    restart: unless-stopped
    ports:
      - "3567:3567"
    environment:
      POSTGRESQL_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRESQL_HOST: ${POSTGRES_HOST}
      POSTGRESQL_PORT: ${POSTGRES_PORT}
      POSTGRESQL_PASSWORD: ${POSTGRES_PASSWORD}

  web:
    image: "azourelli/anicafe-webapp"
    restart: unless-stopped
    ports:
      - 3000:3000

  api:
    build: "azourelli/anicafe-server"
    restart: unless-stopped
    ports:
      - 4000:4000
    environment:
      POSTGRESQL_USER: ${POSTGRES_USER}
      POSTGRESQL_HOST: ${POSTGRES_HOST}
      POSTGRESQL_PORT: ${POSTGRES_PORT}
      POSTGRESQL_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE_URL: ${POSTGRES_DATABASE_URL}
      NODE_DEV: false
      POSTGRES_DATABASE_URL_OWNER: ${POSTGRES_DATABASE_URL_OWNER}

  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    ports:
      - 80:80
      - 443:443
    environment:
      - NAMECHEAP_API_USER=${NAMECHEAP_API_USER}
      - NAMECHEAP_API_KEY=${NAMECHEAP_API_KEY}
    env_file: .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/traefik.yml:./traefik/traefik.yml:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=web"
      - "traefik.http.routers.traefik.rule=Host(`dashboard.ani.cafe`)"
      - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.traefik-secure.entrypoints=websocket"
      - "traefik.http.routers.traefik-secure.rule=Host(`dashboard.ani.cafe`)"
      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.routers.traefik-secure.tls.certresolver=namecheap"
      - "traefik.http.routers.traefik-secure.tls.domains[0].main=ani.cafe"
      - "traefik.http.routers.traefik-secure.tls.domains[0].sans=*.ani.cafe"
      - "traefik.http.routers.traefik-secure.service=api@internal"
