version: "3.8"
services:
  db:
    image: "postgres"
    container_name: "anime-postgres"
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: anime
    ports:
      - "5433:5432"
    volumes:
      - ./pg-data:/var/lib/postgresql/data
  supertokens:
    image: "registry.supertokens.io/supertokens/supertokens-postgresql"
    container_name: "supertokens"
    restart: always
    ports:
      - "3567:3567"
    environment:
      POSTGRESQL_USER: admin
      POSTGRESQL_HOST: db
      POSTGRESQL_PORT: 5432
      POSTGRESQL_PASSWORD: admin

  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    environment:
      - NAMECHEAP_API_USER=${NAMECHEAP_API_USER}
      - NAMECHEAP_API_KEY=${NAMECHEAP_API_KEY}
    env_file: .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-secure.entrypoints=web"
      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.routers.traefik-secure.rule=Host(`dashboard.localhost`)"
      - "traefik.http.routers.dashboard.service=api@internal"
      # - "traefik.port=8080"
