global:
  checkNewVersion: true
  sendAnonymousUsage: true
api:
  dashboard: true
  insecure: true
log:
  level: DEBUG
ping: {}
entryPoints:
  web:
    address: :80
    # http:
    #   redirections:
    #     entryPoint:
    #       to: websecure
    #       scheme: https
  websecure:
    address: :443
# certificateResolvers:
#   namecheapResolver:
#     acme:
#       email: "azourelli@gmail.com"
#       storage: "acme.json"
#       dnsChallenge:
#         provider: namecheap
#         resolvers:
#           - "1.1.1.1:53"
#           - "1.0.0.1:53"
providers:
  docker: {}
  # file:
  #   filename: /traefik/config.yml
